version: '3'

networks:
  dns-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.0.0/16

services:
  bind9:
    container_name: dns-server
    image: ubuntu/bind9:latest
    environment:
      - BIND9_USER=root
      - TZ=Europe/Moscow
    networks:
      dns-network:
        ipv4_address: 10.20.3.2
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./config:/etc/bind
      - ./cache:/var/cache/bind
      - ./records:/var/lib/bind
    restart: unless-stopped
